# Generated by Django 6.0.7 on 2026-07-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('prep_level', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('problem_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.problemset')),
            ],
        ),
    ]
