# Generated by Django 6.0.7 on 2026-08-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_problemset_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='curr_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='prep_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
