# Generated by Django 6.0.7 on 2026-08-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_curr_tag_question_difficulty_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
