# Generated by Django 6.0.7 on 2026-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_problemset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='difficulty_tag',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='prep_tag',
            new_name='prep_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='curr_tag',
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
