# Generated by Django 6.0.7 on 2026-08-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_difficulty_tag_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='problemset',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='problemset',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problemset',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
