# Generated by Django 6.0.7 on 2026-08-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_problemset_options_problemset_form_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('page', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
