# Generated by Django 6.0.7 on 2026-08-31 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='parent_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='api.problemset'),
        ),
        migrations.AddField(
            model_name='problemset',
            name='version_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
