# Generated by Django 6.0.7 on 2026-09-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_problemset_parent_set_problemset_version_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='teacher_tips',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
