# Generated by Django 6.0.7 on 2026-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_problemset_teacher_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='teacher_tips',
        ),
        migrations.AddField(
            model_name='question',
            name='teacher_tip',
            field=models.TextField(blank=True, default=''),
        ),
    ]
