# Generated by Django 6.0.7 on 2026-09-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_problemset_teacher_tips_question_teacher_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='output_overrides',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
