import type { PrepLevel } from '../types/problem';

export type CurriculumData = Partial<Record<PrepLevel, Record<string, string[]>>>;

export const CURRICULUM_DATA: CurriculumData = {
  'Sec III': {
    'Statistics': [
      'Sampling methods: survey, census, stratified, cluster',
      'Experimental and theoretical data',
      'Organizing data: table of condensed data, grouped into classes, histogram, box-and-whisker plot',
      'Measures of central tendency: mode, median, weighted mean',
      'Measures of dispersion: range, interquartile range',
    ],
    'Probability': [
      'Continuous or discrete random variable',
      'Theoretical and experimental probability',
      'Probability of an event',
      'Simple arrangement, permutation, combination (based on reasoning, not formulas)',
      'Geometric probability',
    ],
    'Numbers & Algebra': [
      'Exponential notation',
      'Scientific notation',
      'Laws of exponents',
      'Cube roots and irrational numbers',
      'Polynomial operations',
      'Factoring: Finding the common factor',
      'Solving first-degree equations in one variable',
      'Inequalities, set notation, interval notation, number line',
      'Solving inequalities',
    ],
    'Relations & Functions': [
      'Relation, function and inverse of a function',
      'Independent and dependent variables',
      'Types of representations (table of values, graph, equation, mapping)',
      'Properties of functions in context',
      'Direct, partial, inverse (rational), constant',
      'Finding the rule of a first degree polynomial function',
      'Modeling a situation using linear function',
    ],
    'Systems of Equations': [
      'Constructing a system of equations',
      'Solving a system of equations: by graphing, using a table of values, and comparison method',
    ],
    'Area of Solids & Spatial Sense': [
      'Pythagorean Theorem',
      'Nets and Area',
      'SI units and conversion',
      'Projection and perspective',
      'Prisms, pyramids, cylinders review',
      'Right circular cone and sphere',
      'Decomposable solids',
      'Lateral area and total area',
      'Similar figures',
    ],
    'Volume of solids': [
      'Area and volume',
      'Capacity, SI units, and conversion',
      'Volume of a right prism and cylinder',
      'Volume of a right pyramid, cone and sphere',
      'Volume of a decomposable solid',
      'Similar solids',
    ],
  },
  'Sec IV (CST)': {
    'Lines and Analytic Geometry': [
      'Slope',
      'Find the equation of a line functional form',
      'General form of the equation of a line',
      'Intercepts',
      'Systems of equations',
      'Particular cases of systems of equations',
      'Parallel and perpendicular lines',
      'Distance between two points',
      'Division point',
      'Analytic proofs',
    ],
    'From functions to modeling': [
      'Real functions (notation, properties)',
      'Second-degree polynomial functions y = ax2',
      'Exponential functions y = acx',
      'Step functions (interpret)',
      'Periodic functions (no equation)',
      'Piecewise functions',
    ],
    'Statistical measures and linear correlation': [
      'Single-variable distribution',
      'Measure of dispersion: mean deviation',
      'Stem-and-leaf plot',
      'Measures of position: percentile rank',
      'Two-variable distributions',
      'Correlation (interpret, coefficient)',
      'Regression line',
    ],
    'From congruent to similar figures': [
      'Congruent/isometric triangles',
      'Similar triangles',
      'Metric relations in right triangles',
    ],
    'Trigonometry': [
      'Trigonometric ratios',
      'Solving a right triangle',
      'Sine law',
      'Area of a triangle (3 formulas)',
    ],
  },
  'Sec IV (SN)': {
    'Algebra and Equivalence': [
      'Multiplying algebraic expressions',
      'Division of polynomials',
      'Algebraic identities – 2nd degree',
      'Factoring polynomials',
      'Rational expressions',
      'Solving 2nd degree equations with one variable',
      'Concept of equivalent figures',
      'Properties of equivalent figures',
      'Equivalent algebraic expressions',
    ],
    'Quadratic functions and trajectories': [
      'Standard form',
      'Role of parameters a, h and k',
      'Patterns and properties',
      'General form',
      'Role of parameters a, b and c',
      'Zeros of the quadratic function',
      'Factored form',
      'Inequalities with a quadratic function',
      'Solving a 2nd degree inequality with one variable',
    ],
    'Statistical measures and linear correlation': [
      'Two-variable distributions',
      'Correlation (interpret, coefficient)',
      'Regression line',
    ],
    'Greatest integer function': [
      'Transformed Greatest Integer function',
    ],
    'Analytic Geometry': [
      'Slope',
      'Find the equation of a line functional form',
      'General form of the equation of a line',
      'Intercepts',
      'Systems of equations',
      'Particular cases of systems of equations',
      'Parallel and perpendicular lines',
      'System of two equations – linear and quadratic',
      'Inequalities in two variables',
      'Solving inequalities in two variables',
      'Half-planes',
      'Distance between two points',
      'Analytic proofs',
    ],
    'Geometric reasoning/proofs': [
      'Congruent triangles',
      'Similar triangles',
      'Metric relations in right triangles',
    ],
    'Trigonometry': [
      'Trigonometric relations',
      'Sine law',
      'Cosine law',
      'Area of a triangle (3 formulas)',
    ],
  },
  'Sec V (CST)': {
    'Graphs': [
      'Tree diagrams and networks',
      'Graph',
      'Connected graph',
      'Complete graph',
      'Paths',
      'Circuits',
      'Trees',
      'Directed graph',
      'Weighted graph',
      'Path of minimum value',
      'Tree of minimum value',
      'Chromatic number',
      'Critical path',
    ],
    'Systems of Equations and Inequalities': [
      'Solving systems of equations',
      'Inequalities in the 1st degree with two variables',
      'System of inequalities',
      'Polygon of constraints',
      'The optimizing function',
      'Optimal solutions',
      'Linear programming and optimal solutions',
      'Solving an optimization problem',
    ],
    'Financial mathematics': [
      'Exponential notation',
      'Laws of exponents',
      'Logarithm (definition and change of base)',
      'Interest rates',
      'Interest period',
      'Discounting',
      'Compounding',
    ],
    'Voting procedures': [
      'Majority rule and plurality voting',
      'Borda count, Condorcet method, elimination method and approval voting',
      'Majority election',
    ],
    'Cosine Law and Equivalent Figures': [
      'Cosine Law',
      'Area of a figure',
      'Volume of a solid',
      'Equivalent lines',
      'Equivalent plane figures',
      'Equivalent solids',
      'Comparing equivalent plane figures',
      'Comparing equivalent solids',
    ],
    'Probability': [
      'Random experiment',
      'Probability of an event',
      'Theoretical, experimental and subjective probability',
      'Odds for and odds against',
      'Distinction between odds and probability',
      'Mathematical expectation (interprets and decision making)',
      'Fairness and optimizing gain or loss',
      'Mutually exclusive events',
      'Non-mutually exclusive events',
      'Independent and dependent events',
      'Conditional probability',
    ],
  },
  'Sec V (SN)': {
    'Vectors': [
      'Scalar quantity and vector quantity',
      'Properties of vectors',
      'Relations between vectors',
      'Vector projection',
      'Addition and subtraction of vectors',
      'Multiplication of a vector by a scalar',
      'Linear combinations',
      'Scalar product of two vectors',
      'Chasles relation',
    ],
    'Systems of Equations and Inequalities': [
      'Solving systems of equations',
      'Inequalities in the 1st degree with two variables',
      'System of inequalities',
      'Polygon of constraints',
      'Optimizing function',
      'Optimal solutions',
      'Solving an optimization problem',
    ],
    'Functions': [
      'The role of parameters',
      'Inverse of a function',
      'Piecewise functions',
      'Properties of radicals',
      'Square root functions',
      'Finding the rule and solving a square root function',
      'Properties of absolute values',
      'Absolute value functions',
      'Finding the rule and solving an absolute value function',
      'Rational functions',
      'Finding the rule and solving a rational function',
      'Operations and composition of functions',
    ],
    'Exponential and Logarithmic Functions': [
      'Laws of exponents and exponential notation',
      'Exponential function',
      'Finding the rule of an exponential function',
      'Logarithms and properties of logs',
      'Logarithmic function',
      'Finding the rule of a logarithmic function',
      'Solving an exponential equations and inequalities',
      'Solving a logarithmic equations and inequalities',
    ],
    'Trigonometric functions': [
      'Radian',
      'Unit circle',
      'Periodic functions',
      'Sinusoidal functions',
      'Finding the rule of a sinusoidal functions',
      'Tangent functions',
      'Finding the rule of a tangent function',
      'Solving first degree trigonometric equations and inequalities',
      'Trigonometric identities (Pythagorean)',
    ],
    'Conics': [
      'Geometric loci',
      'Circle and finding its equation',
      'Interior or exterior region of a circle',
      'Ellipse and finding its equation',
      'Interior or exterior region of an ellipse',
      'Hyperbola and finding its equation',
      'Interior or exterior region of a hyperbola',
      'Parabola and finding its equation',
      'Interior or exterior region of a parabola',
      'Intersection points of a line and a conic or a parabola and another conic',
    ],
  },
};